version: '3.6'

services:
  test-redis:
    image: redis:alpine
    container_name: test-cache
    expose:
      - 6379
    restart: always

  test-back:
    image: node
    command: sh -c "cd /back && npm i && npm start"
    volumes:
      - ./app-back:/back
      - /back/node_modules/
      - public:/back/public
    ports:
      - 3000:3000
    environment:
      - NODE_ENV
      - PORT
      - REDIS_URL
      - API_ROUTE

  test-front:
    image: node:12.13.0-alpine
    command: sh -c "cd /front && npm i && npm run build && mv -v dist/* /back/public/"
    volumes:
      - ./app-front:/front
      - /front/node_modules/
      - public:/back/public
    environment:
      - NODE_ENV

volumes:
  public:
